# Generated by Django 3.2.9 on 2021-11-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
