# Generated by Django 3.2.9 on 2021-11-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_rename_descrição_transacao_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
